networks:
  ecommerce:
    external: true

services:
  catalog-db:
    image: mysql:8
    container_name: catalog-db
    environment:
      MYSQL_ROOT_PASSWORD: 9816
      MYSQL_DATABASE: catalog_db
    ports:
      - "3315:3306"
    networks:
      - ecommerce
