networks:
  ecommerce:
    external: true

services:
  user-db:
    image: mysql:8
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: 9816
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    networks:
      - ecommerce

  orders-db:
    image: mysql:8
    container_name: orders-db
    environment:
      MYSQL_ROOT_PASSWORD: 9816
      MYSQL_DATABASE: orders_db
    ports:
      - "3309:3306"
    networks:
      - ecommerce

  catalog-db:
    image: mysql:8
    container_name: catalog-db
    environment:
      MYSQL_ROOT_PASSWORD: 9816
      MYSQL_DATABASE: catalog_db
    ports:
      - "3315:3306"
    networks:
      - ecommerce
